import { NextResponse } from 'next/server';

// Define the JSON data as a TypeScript object
const psalms = {
  "1": {
    "title": "Psalm 1",
    "text": "Blessed is the man who walks not in the counsel of the wicked,\nnor stands in the way of sinners,\nnor sits in the seat of scoffers;\nbut his delight is in the law of the Lord,\nand on his law he meditates day and night.\nHe is like a tree planted by streams of water\nthat yields its fruit in its season,\nand its leaf does not wither.\nIn all that he does, he prospers.\nThe wicked are not so,\nbut are like chaff that the wind drives away.\nTherefore the wicked will not stand in the judgment,\nnor sinners in the congregation of the righteous;\nfor the Lord knows the way of the righteous,\nbut the way of the wicked will perish."
  },
  "2": {
    "title": "Psalm 2",
    "text": "Why do the nations rage and the peoples plot in vain?\nThe kings of the earth set themselves,\nand the rulers take counsel together,\nagainst the Lord and against his Anointed,\nsaying, “Let us burst their bonds apart\nand cast away their cords from us.”\nHe who sits in the heavens laughs;\nthe Lord holds them in derision.\nThen he will speak to them in his wrath,\nand terrify them in his fury,\nsaying, “As for me, I have set my King on Zion,\nmy holy hill.”\nI will tell of the decree:\nThe Lord said to me, “You are my Son;\ntoday I have begotten you.\nAsk of me, and I will make the nations your heritage,\nand the ends of the earth your possession.\nYou shall break them with a rod of iron\nand dash them in pieces like a potter’s vessel.”\nNow therefore, O kings, be wise;\nbe warned, O rulers of the earth.\nServe the Lord with fear,\nand rejoice with trembling.\nKiss the Son, lest he be angry,\nand you perish in the way,\nfor his wrath is quickly kindled.\nBlessed are all who take refuge in him."
  },
  "3": {
    "title": "Psalm 3",
    "text": "O Lord, how many are my foes!\nMany are rising against me;\nmany are saying of my soul,\nthere is no salvation for him in God. Selah.\nBut you, O Lord, are a shield about me,\nmy glory, and the lifter of my head.\nI cried aloud to the Lord,\nand he answered me from his holy hill. Selah.\nI lay down and slept;\nI woke again, for the Lord sustained me.\nI will not be afraid of many thousands of people\nwho have set themselves against me all around.\nArise, O Lord! Save me, O my God!\nFor you strike all my enemies on the cheek;\nyou break the teeth of the wicked.\nSalvation belongs to the Lord;\nyour blessing be on your people! Selah."
  },
  "4": {
    "title": "Psalm 4",
    "text": "Answer me when I call, O God of my righteousness!\nYou have given me relief when I was in distress.\nBe gracious to me and hear my prayer!\nO men, how long shall my honor be turned into shame?\nHow long will you love vain words and seek after lies? Selah.\nBut know that the Lord has set apart the godly for himself;\nthe Lord hears when I call to him.\nBe angry, and do not sin;\nponder in your own hearts on your beds,\nand be silent. Selah.\nOffer right sacrifices,\nand put your trust in the Lord.\nThere are many who say, “Who will show us some good?\nLift up the light of your face upon us, O Lord!”\nYou have put more joy in my heart\nthan they have when their grain and wine abound.\nIn peace I will both lie down and sleep;\nfor you alone, O Lord, make me dwell in safety."
  },
  "5": {
    "title": "Psalm 5",
    "text": "Give ear to my words, O Lord;\nconsider my groaning.\nGive attention to the sound of my cry,\nmy King and my God,\nfor to you do I pray.\nO Lord, in the morning you hear my voice;\nin the morning I prepare a sacrifice for you and watch.\nFor you are not a God who delights in wickedness;\nevil may not dwell with you.\nThe boastful shall not stand before your eyes;\nyou hate all evildoers.\nYou destroy those who speak lies;\nthe Lord abhors the bloodthirsty and deceitful man.\nBut I, through the abundance of your steadfast love,\nwill enter your house.\nI will bow down toward your holy temple in the fear of you.\nLead me, O Lord, in your righteousness because of my enemies;\nmake your way straight before me.\nFor there is no truth in their mouth;\ntheir inmost self is destruction;\ntheir throat is an open grave;\nthey flatter with their tongue.\nMake them bear their guilt, O God;\nlet them fall by their own counsels;\nbecause of the abundance of their transgressions cast them out,\nfor they have rebelled against you.\nBut let all who take refuge in you rejoice;\nlet them ever sing for joy,\nand spread your protection over them,\nthat those who love your name may exult in you.\nFor you bless the righteous, O Lord;\nyou cover him with favor as with a shield."
  },
  "6": {
    "title": "Psalm 6",
    "text": "O Lord, rebuke me not in your anger,\nnor discipline me in your wrath.\nBe gracious to me, O Lord, for I am languishing;\nheal me, O Lord, for my bones are troubled.\nMy soul also is greatly troubled.\nBut you, O Lord—how long?\nTurn, O Lord, deliver my life;\nsave me for the sake of your steadfast love.\nFor in death there is no remembrance of you;\nin Sheol who will give you praise?\nI am weary with my moaning;\nevery night I flood my bed with tears;\nI drench my couch with my weeping.\nMy eye wastes away because of grief;\nit grows weak because of all my foes.\nDepart from me, all you workers of evil,\nfor the Lord has heard the sound of my weeping.\nThe Lord has heard my plea;\nthe Lord accepts my prayer.\nAll my enemies shall be ashamed and greatly troubled;\nthey shall turn back and be put to shame in a moment."
  },
  "7": {
    "title": "Psalm 7",
    "text": "O Lord my God, in you do I take refuge;\nsave me from all my pursuers and deliver me,\nlest like a lion they tear my soul apart,\nrending it in pieces, with none to deliver.\nO Lord my God, if I have done this,\nif there is wrong in my hands,\nif I have repaid my friend with evil\nor plundered my enemy without cause,\nlet the enemy pursue my soul and overtake it,\nand let him trample my life to the ground\nand lay my glory in the dust. Selah.\nArise, O Lord, in your anger;\nlift yourself up against the fury of my enemies;\nawake for me; you have appointed a judgment.\nLet the assembly of the peoples be gathered about you;\nover it return on high.\nThe Lord judges the peoples;\njudge me, O Lord, according to my righteousness\nand according to the integrity that is in me.\nOh, let the evil of the wicked come to an end,\nand may you establish the righteous—\nyou who test the minds and hearts, O righteous God!\nMy shield is with God, who saves the upright in heart.\nGod is a righteous judge,\nand a God who feels indignation every day.\nIf a man does not repent, God will whet his sword;\nhe has bent and readied his bow;\nhe has prepared for him his deadly weapons,\nmaking his arrows fiery shafts.\nBehold, the wicked man conceives evil\nand is pregnant with mischief and gives birth to lies.\nHe makes a pit, digging it out,\nand falls into the hole that he has made.\nHis mischief returns upon his own head,\nand on his own skull his violence descends.\nI will give to the Lord the thanks due to his righteousness,\nand I will sing praise to the name of the Lord, the Most High."
  },
  "8": {
    "title": "Psalm 8",
    "text": "O Lord, our Lord, how majestic is your name in all the earth!\nYou have set your glory above the heavens.\nOut of the mouth of babes and infants,\nyou have established strength because of your foes,\nto still the enemy and the avenger.\nWhen I look at your heavens, the work of your fingers,\nthe moon and the stars, which you have set in place,\nwhat is man that you are mindful of him,\nand the son of man that you care for him?\nYet you have made him a little lower than the heavenly beings\nand crowned him with glory and honor.\nYou have given him dominion over the works of your hands;\nyou have put all things under his feet,\nall sheep and oxen,\nand also the beasts of the field,\nthe birds of the heavens,\nand the fish of the sea,\nwhatever passes along the paths of the seas.\nO Lord, our Lord, how majestic is your name in all the earth!"
  },
  "9": {
    "title": "Psalm 9",
    "text": "I will give thanks to the Lord with my whole heart;\nI will recount all of your wonderful deeds.\nI will be glad and exult in you;\nI will sing praise to your name, O Most High.\nWhen my enemies turn back,\nthey stumble and perish before your presence.\nFor you have maintained my just cause;\nyou have sat on the throne, giving righteous judgment.\nYou have rebuked the nations;\nyou have made the wicked perish;\nyou have blotted out their name forever and ever.\nThe enemy came to an end in everlasting ruins;\ntheir cities you rooted out;\nthe very memory of them has perished.\nBut the Lord sits enthroned forever;\nhe has established his throne for justice,\nand he judges the world with righteousness;\nhe judges the peoples with uprightness.\nThe Lord is a stronghold for the oppressed,\na stronghold in times of trouble.\nAnd those who know your name put their trust in you,\nfor you, O Lord, have not forsaken those who seek you.\nSing praises to the Lord, who sits enthroned in Zion!\nTell among the peoples his deeds!\nFor he who avenges blood is mindful of them;\nhe does not forget the cry of the afflicted.\nBe gracious to me, O Lord!\nSee my affliction from those who hate me,\nO you who lift me up from the gates of death,\nthat I may recount all your praises,\nthat in the gates of the daughter of Zion I may rejoice in your salvation.\nThe nations have sunk in the pit that they made;\nin the net that they hid, their own foot has been caught.\nThe Lord has made himself known;\nhe has executed judgment;\nthe wicked are snared in the work of their own hands. Selah.\nThe wicked shall return to Sheol,\nall the nations that forget God.\nFor the needy shall not always be forgotten,\nand the hope of the poor shall not perish forever.\nArise, O Lord!\nLet not man prevail;\nlet the nations be judged before you!\nPut them in fear, O Lord!\nLet the nations know that they are but men! Selah."
  },
  "10": {
    "title": "Psalm 10",
    "text": "Why, O Lord, do you stand far away?\nWhy do you hide yourself in times of trouble?\nIn arrogance the wicked hotly pursue the poor;\nlet them be caught in the schemes that they have devised.\nFor the wicked boasts of the desires of his soul,\nand the one greedy for gain curses and renounces the Lord.\nIn the pride of his face the wicked does not seek him;\nall his thoughts are, “There is no God.”\nHis ways prosper at all times;\nyour judgments are on high, out of his sight;\nas for all his foes, he puffs at them.\nHe says in his heart, “I shall not be moved;\nthroughout all generations I shall not meet adversity.”\nHis mouth is filled with cursing and deceit and oppression;\nunder his tongue are mischief and iniquity.\nHe sits in ambush in the villages;\nin hiding places he murders the innocent.\nHis eyes stealthily watch for the helpless;\nhe lurks in ambush like a lion in his thicket;\nhe lurks that he may seize the poor;\nhe seizes the poor when he draws him into his net.\nThe helpless are crushed, sink down, and fall by his might.\nHe says in his heart, “God has forgotten,\nhe has hidden his face, he will never see it.”\nArise, O Lord; O God, lift up your hand;\nforget not the afflicted.\nWhy does the wicked renounce God and say in his heart,\n“You will not call to account”? But you do see,\nfor you note mischief and vexation,\nthat you may take it into your hands;\nto you the helpless commits himself;\nyou have been the helper of the fatherless.\nBreak the arm of the wicked and evildoer;\ncall his wickedness to account till you find none.\nThe Lord is king forever and ever;\nthe nations perish from his land.\nO Lord, you hear the desire of the afflicted;\nyou will strengthen their heart;\nyou will incline your ear\nto do justice to the fatherless and the oppressed,\nso that man who is of the earth may strike terror no more."
  }
}
;

export async function GET() {
    return NextResponse.json(psalms);
  }