import { NextResponse } from 'next/server';


// Define the JSON data with verse numbers
const psalms = {
  "1": {
    "title": "Psalm 1",
    "text": "1 Blessed is the man who walks not in the counsel of the wicked,\n2 nor stands in the way of sinners,\n3 nor sits in the seat of scoffers;\n4 but his delight is in the law of the Lord,\n5 and on his law he meditates day and night.\n6 He is like a tree planted by streams of water\n7 that yields its fruit in its season,\n8 and its leaf does not wither.\n9 In all that he does, he prospers.\n10 The wicked are not so,\n11 but are like chaff that the wind drives away.\n12 Therefore the wicked will not stand in the judgment,\n13 nor sinners in the congregation of the righteous;\n14 for the Lord knows the way of the righteous,\n15 but the way of the wicked will perish."
  },
  "2": {
    "title": "Psalm 2",
    "text": "1 Why do the nations rage and the peoples plot in vain?\n2 The kings of the earth set themselves,\n3 and the rulers take counsel together,\n4 against the Lord and against his Anointed,\n5 saying, “Let us burst their bonds apart\n6 and cast away their cords from us.”\n7 He who sits in the heavens laughs;\n8 the Lord holds them in derision.\n9 Then he will speak to them in his wrath,\n10 and terrify them in his fury,\n11 saying, “As for me, I have set my King on Zion,\n12 my holy hill.”\n13 I will tell of the decree:\n14 The Lord said to me, “You are my Son;\n15 today I have begotten you.\n16 Ask of me, and I will make the nations your heritage,\n17 and the ends of the earth your possession.\n18 You shall break them with a rod of iron\n19 and dash them in pieces like a potter’s vessel.”\n20 Now therefore, O kings, be wise;\n21 be warned, O rulers of the earth.\n22 Serve the Lord with fear,\n23 and rejoice with trembling.\n24 Kiss the Son, lest he be angry,\n25 and you perish in the way,\n26 for his wrath is quickly kindled.\n27 Blessed are all who take refuge in him."
  },
  "3": {
    "title": "Psalm 3",
    "text": "1 O Lord, how many are my foes!\n2 Many are rising against me;\n3 many are saying of my soul,\n4 there is no salvation for him in God. Selah.\n5 But you, O Lord, are a shield about me,\n6 my glory, and the lifter of my head.\n7 I cried aloud to the Lord,\n8 and he answered me from his holy hill. Selah.\n9 I lay down and slept;\n10 I woke again, for the Lord sustained me.\n11 I will not be afraid of many thousands of people\n12 who have set themselves against me all around.\n13 Arise, O Lord! Save me, O my God!\n14 For you strike all my enemies on the cheek;\n15 you break the teeth of the wicked.\n16 Salvation belongs to the Lord;\n17 your blessing be on your people! Selah."
  },
  "4": {
    "title": "Psalm 4",
    "text": "1 Answer me when I call, O God of my righteousness!\n2 You have given me relief when I was in distress.\n3 Be gracious to me and hear my prayer!\n4 O men, how long shall my honor be turned into shame?\n5 How long will you love vain words and seek after lies? Selah.\n6 But know that the Lord has set apart the godly for himself;\n7 the Lord hears when I call to him.\n8 Be angry, and do not sin;\n9 ponder in your own hearts on your beds,\n10 and be silent. Selah.\n11 Offer right sacrifices,\n12 and put your trust in the Lord.\n13 There are many who say, “Who will show us some good?\n14 Lift up the light of your face upon us, O Lord!”\n15 You have put more joy in my heart\n16 than they have when their grain and wine abound.\n17 In peace I will both lie down and sleep;\n18 for you alone, O Lord, make me dwell in safety."
  },
  "5": {
    "title": "Psalm 5",
    "text": "1 Give ear to my words, O Lord;\n2 consider my groaning.\n3 Give attention to the sound of my cry,\n4 my King and my God,\n5 for to you do I pray.\n6 O Lord, in the morning you hear my voice;\n7 in the morning I prepare a sacrifice for you and watch.\n8 For you are not a God who delights in wickedness;\n9 evil may not dwell with you.\n10 The boastful shall not stand before your eyes;\n11 you hate all evildoers.\n12 You destroy those who speak lies;\n13 the Lord abhors the bloodthirsty and deceitful man.\n14 But I, through the abundance of your steadfast love,\n15 will enter your house.\n16 I will bow down toward your holy temple in the fear of you.\n17 Lead me, O Lord, in your righteousness because of my enemies;\n18 make your way straight before me.\n19 For there is no truth in their mouth;\n20 their inmost self is destruction;\n21 their throat is an open grave;\n22 they flatter with their tongue.\n23 Make them bear their guilt, O God;\n24 let them fall by their own counsels;\n25 because of the abundance of their transgressions cast them out,\n26 for they have rebelled against you.\n27 But let all who take refuge in you rejoice;\n28 let them ever sing for joy,\n29 and spread your protection over them,\n30 that those who love your name may exult in you.\n31 For you bless the righteous, O Lord;\n32 you cover him with favor as with a shield."
  },
  "6": {
    "title": "Psalm 6",
    "text": "1 O Lord, rebuke me not in your anger,\n2 nor discipline me in your wrath.\n3 Be gracious to me, O Lord, for I am languishing;\n4 heal me, O Lord, for my bones are troubled.\n5 My soul also is greatly troubled.\n6 But you, O Lord—how long?\n7 Turn, O Lord, deliver my life;\n8 save me for the sake of your steadfast love.\n9 For in death there is no remembrance of you;\n10 in Sheol who will give you praise?\n11 I am weary with my moaning;\n12 every night I flood my bed with tears;\n13 I drench my couch with my weeping.\n14 My eye wastes away because of grief;\n15 it grows weak because of all my foes.\n16 Depart from me, all you workers of evil,\n17 for the Lord has heard the sound of my weeping.\n18 The Lord has heard my plea;\n19 the Lord accepts my prayer.\n20 All my enemies shall be ashamed and greatly troubled;\n21 they shall turn back and be put to shame in a moment."
  },
  "7": {
    "title": "Psalm 7",
    "text": "1 O Lord my God, in you do I take refuge;\n2 save me from all my pursuers and deliver me,\n3 lest like a lion they tear my soul apart,\n4 rending it in pieces, with none to deliver.\n5 O Lord my God, if I have done this,\n6 if there is wrong in my hands,\n7 if I have repaid my friend with evil\n8 or plundered my enemy without cause,\n9 let the enemy pursue my soul and overtake it,\n10 and let him trample my life to the ground\n11 and lay my glory in the dust. Selah.\n12 Arise, O Lord, in your anger;\n13 lift yourself up against the fury of my enemies;\n14 awake for me; you have appointed a judgment.\n15 Let the assembly of the peoples be gathered about you;\n16 over it return on high.\n17 The Lord judges the peoples;\n18 judge me, O Lord, according to my righteousness\n19 and according to the integrity that is in me.\n20 Oh, let the evil of the wicked come to an end,\n21 and may you establish the righteous—\n22 you who test the minds and hearts, O righteous God!\n23 My shield is with God, who saves the upright in heart.\n24 God is a righteous judge,\n25 and a God who feels indignation every day.\n26 If a man does not repent, God will whet his sword;\n27 he has bent and readied his bow;\n28 he has prepared for him his deadly weapons,\n29 making his arrows fiery shafts.\n30 Behold, the wicked man conceives evil\n31 and is pregnant with mischief and gives birth to lies.\n32 He makes a pit, digging it out,\n33 and falls into the hole that he has made.\n34 His mischief returns upon his own head,\n35 and on his own skull his violence descends.\n36 I will give to the Lord the thanks due to his righteousness,\n37 and I will sing praise to the name of the Lord, the Most High."
  },
  "8": {
    "title": "Psalm 8",
    "text": "1 O Lord, our Lord, how majestic is your name in all the earth!\n2 You have set your glory above the heavens.\n3 Out of the mouth of babes and infants,\n4 you have established strength because of your foes,\n5 to still the enemy and the avenger.\n6 When I look at your heavens, the work of your fingers,\n7 the moon and the stars, which you have set in place,\n8 what is man that you are mindful of him,\n9 and the son of man that you care for him?\n10 Yet you have made him a little lower than the heavenly beings\n11 and crowned him with glory and honor.\n12 You have given him dominion over the works of your hands;\n13 you have put all things under his feet,\n14 all sheep and oxen,\n15 and also the beasts of the field,\n16 the birds of the heavens,\n17 and the fish of the sea,\n18 whatever passes along the paths of the seas.\n19 O Lord, our Lord, how majestic is your name in all the earth!"
  },
  "9": {
    "title": "Psalm 9",
    "text": "1 I will give thanks to the Lord with my whole heart;\n2 I will recount all of your wonderful deeds.\n3 I will be glad and exult in you;\n4 I will sing praise to your name, O Most High.\n5 When my enemies turn back,\n6 they stumble and perish before your presence.\n7 For you have maintained my just cause;\n8 you have sat on the throne, giving righteous judgment.\n9 You have rebuked the nations;\n10 you have made the wicked perish;\n11 you have blotted out their name forever and ever.\n12 The enemy came to an end in everlasting ruins;\n13 their cities you rooted out;\n14 the very memory of them has perished.\n15 But the Lord sits enthroned forever;\n16 he has established his throne for justice,\n17 and he judges the world with righteousness;\n18 he judges the peoples with uprightness.\n19 The Lord is a stronghold for the oppressed,\n20 a stronghold in times of trouble.\n21 And those who know your name put their trust in you,\n22 for you, O Lord, have not forsaken those who seek you.\n23 Sing praises to the Lord, who sits enthroned in Zion!\n24 Tell among the peoples his deeds!\n25 For he who avenges blood is mindful of them;\n26 he does not forget the cry of the afflicted.\n27 Be gracious to me, O Lord!\n28 See my affliction from those who hate me,\n29 O you who lift me up from the gates of death,\n30 that I may recount all your praises,\n31 that in the gates of the daughter of Zion I may rejoice in your salvation.\n32 The nations have sunk in the pit that they made;\n33 in the net that they hid, their own foot has been caught.\n34 The Lord has made himself known;\n35 he has executed judgment;\n36 the wicked are snared in the work of their own hands. Selah.\n37 The wicked shall return to Sheol,\n38 all the nations that forget God.\n39 For the needy shall not always be forgotten,\n40 and the hope of the poor shall not perish forever.\n41 Arise, O Lord!\n42 Let not man prevail;\n43 let the nations be judged before you!\n44 Put them in fear, O Lord!\n45 Let the nations know that they are but men! Selah."
  },
  "10": {
    "title": "Psalm 10",
    "text": "1 Why, O Lord, do you stand far away?\n2 Why do you hide yourself in times of trouble?\n3 In arrogance the wicked hotly pursue the poor;\n4 let them be caught in the schemes that they have devised.\n5 For the wicked boasts of the desires of his soul,\n6 and the one greedy for gain curses and renounces the Lord.\n7 In the pride of his face the wicked does not seek him;\n8 all his thoughts are, “There is no God.”\n9 His ways prosper at all times;\n10 your judgments are on high, out of his sight;\n11 as for all his foes, he puffs at them.\n12 He says in his heart, “I shall not be moved;\n13 throughout all generations I shall not meet adversity.”\n14 His mouth is filled with cursing and deceit and oppression;\n15 under his tongue are mischief and iniquity.\n16 He sits in ambush in the villages;\n17 in hiding places he murders the innocent.\n18 His eyes stealthily watch for the helpless;\n19 he lurks in ambush like a lion in his thicket;\n20 he lurks that he may seize the poor;\n21 he seizes the poor when he draws him into his net.\n22 The helpless are crushed, sink down, and fall by his might.\n23 He says in his heart, “God has forgotten,\n24 he has hidden his face, he will never see it.”\n25 Arise, O Lord; O God, lift up your hand;\n26 forget not the afflicted.\n27 Why does the wicked renounce God and say in his heart,\n28 “You will not call to account”? But you do see,\n29 for you note mischief and vexation,\n30 that you may take it into your hands;\n31 to you the helpless commits himself;\n32 you have been the helper of the fatherless.\n33 Break the arm of the wicked and evildoer;\n34 call his wickedness to account till you find none.\n35 The Lord is king forever and ever;\n36 the nations perish from his land.\n37 O Lord, you hear the desire of the afflicted;\n38 you will strengthen their heart;\n39 you will incline your ear\n40 to do justice to the fatherless and the oppressed,\n41 so that man who is of the earth may strike terror no more."
  }
};



export async function GET() {
    return NextResponse.json(psalms);
  }